// <auto-generated />
namespace WebsiteSieuThiMini.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create_table_HangHoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_table_HangHoa));
        
        string IMigrationMetadata.Id
        {
            get { return "202009231823032_Create_table_HangHoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
